# Generated by Django 4.2.7 on 2023-11-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint', '0003_messages_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='edit_time',
        ),
    ]
